model: ufal/robeczech-base
optimizer: !!python/object/apply:functools.partial
  args:
  - &id001 !!python/name:optims.get_no_bias_weight_adamw ''
  state: !!python/tuple
  - *id001
  - !!python/tuple []
  - betas: !!python/tuple
    - 0.9
    - 0.999
    eps: 1.0e-06
    lr: 1.0e-05
    weight_decay: 0.01
  - null
scheduler: null
