run:
  fit: False
  test: False
  validate: False
  tune: False

seed: 42
chckpt_path: null

# Run config
max_epochs: 1
log_every_n_steps: 1000
val_check_interval: 0.2
callbacks: []


defaults:
  - _self_
  - accelerator: cpu_single
  - model: ???
  - optimizer: ???
  - scheduler: ???
  - data: ???
  - run: ???

