seed: 42

run:
  mode: null
  chckpt_path: ???

# Run config
max_epochs: 1
log_every_n_steps: 1000
val_check_interval: 0.2
fast_dev_run: null
limit_train_batches: null
limit_val_batches: null
limit_test_batches: null
callbacks: []

# Batchsize
batch_size: 2
num_proc: 0

accelerator:
  pin_memory: false

# Model
model:
  metrics:
    patience: ???
    monitor: ???
    mode: ???


defaults:
  - _self_
  - accelerator: cpu_single
  - model: ???
  - optimizer: ???
  - scheduler: ???
  - data: ???
  - run: debug