_target_: schedulers.get_linear_schedule_for_discriminiative_lr
num_warmup_steps: 0.1
total_unfreezes: 6
groups_per_unfreeze: 2
num_warmup_steps_classifier: 0.1
num_warmup_steps_backbone: 0.1
min_lr_classifier: 0
min_lr_backbone: 0
