# @package _global_
run:
  mode: fit
  chckpt_path: null
  debug: True


log_every_n_steps: 1
val_check_interval: null
limit_train_batches: 1
limit_val_batches: 1
limit_test_batches: 2
# Don't check effective batch size
effective_batch_size: -1