score_types:
- 'f1_macro'
- 'f1_micro'
- 'accuracy'

n_proc: 4
output_path: "Modelling/Baseline/models"

logger:
  mode: online
run:
  load_model: null
  search: False
  test: False
  train: False


search:
  cv_params: {}


defaults:
  - data: base
  - model: logistic_regression