score_types:
- 'f1_macro'
- 'f1_micro'

n_proc: 4
output_path: "Modelling/Baseline/models"

logger:
  mode: online
  run_id: null
run:
  test: False
  train: False
  eval: False


search:
  cv_params: {}


defaults:
  - data: base
  - model: logistic_regression